language: php
php:
- 5.5
- 5.6
before_script:
- composer install --no-interaction --prefer-dist
script:
- vendor/bin/phpunit --coverage-clover coverage.clover --coverage-html coverage
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
after_success: ./coverage.sh
branches:
  only:
  - master
env:
  global:
  - secure: ebPkHbYy233dQfJhDnzCHIBiqUl5ONrA8f0i2v6sU/kgMM5QhCa/xRDxUlsGYSjp/eyC5epV187gSPS1pjAlLn0gMWtZpMg8G4HrXQh/Q/hBJDfdkpEhqoJHXYvPGv5gntghfXhEWMyECOMcYSLNpL9otRVK5PtZmaNnXPgLhQA=
